AWSTemplateFormatVersion: "2010-09-09"

Transform:
    - "AWS::Serverless-2016-10-31"

Parameters:
    LogLevel:
        Type: "String"
        Default: "INFO"
        AllowedValues:
            - "DEBUG"
            - "INFO"
            - "WARNING"
            - "ERROR"
            - "CRITICAL"

    BinsTableName:
        Type: "String"

    MastercardSecretName:
        Type: "String"

    MastercardApiUrl:
        Type: "String"
        Default: "https://sandbox.api.mastercard.com/"

Resources:
    MasterCardBinsHandler:
        Type: "AWS::Serverless::Function"
        Properties:
            CodeUri: "../target/build/"
            Handler: "index.handler"
            MemorySize: 512
            Runtime: "python3.12"
            Tracing: "Active"
            Timeout: 900
            Environment:
                Variables:
                    LOG_LEVEL: !Ref "LogLevel"
                    BINS_TABLE_NAME: !Ref "BinsTableName"
                    SECRET_NAME: !Ref "MastercardSecretName"
                    API_URL: !Ref "MastercardApiUrl"
            Policies:
                -
                    Version: "2012-10-17"
                    Statement:
                        -
                            Action:
                                - "dynamodb:PutItem"
                            Effect: "Allow"
                            Resource:
                                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${BinsTableName}"
                -
                    Version: "2012-10-17"
                    Statement:
                        -
                            Action:
                                - "secretsmanager:GetSecretValue"
                            Effect: "Allow"
                            Resource:
                                - !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${MastercardSecretName}*"
            Events:
                Schedule:
                    Type: "ScheduleV2"
                    Properties:
                        ScheduleExpression: "rate(1 day)"
